---
title: "gamma_compare_p_vals"
output: html_document
---

```{r}
source("p_values_cont.R")

library(VGAM)
```
```{r}
?seq
```

```{r}
t_obs = 0.5
beta = 2
alpha_0 = 2 / beta

pT <- function(t, shape = alpha_0, scale = beta){
  plgamma(t, shape = shape, scale = scale)}
dT <- function(t, shape = alpha_0, scale = beta){
  dlgamma(t, shape = shape, scale = scale)}
intT <- function(t, shape = alpha_0, scale = beta){
  t*dlgamma(t, shape = shape, scale = scale)}

t_vec <- seq(-5, 5, by = 0.2)
dt_vec <- dT(t_vec)

plot(t_vec, dt_vec)
```

```{r}
t_obs = 1
unbiased_p_val(t_obs, pT, intT)
tail_p_val(t_obs, pT)
point_p_val(t_obs, dT, pT)
```

```{r}
significance_level = 0.005

crit_unbiased <- find_crit_values(unbiased_p_val, significance_value = significance_level, pT, intT, mid_point = 0)
crit_tail <- find_crit_values(tail_p_val, significance_value = significance_level, pT, mid_point = 0)
crit_point <- find_crit_values(point_p_val, significance_value = significance_level, dT, pT, mid_point = -.2)

crit_unbiased
crit_tail
crit_point
```

```{r}
find_power <- function(true_alpha, crit, beta = 2){
  1 - plgamma(crit[2], shape = true_alpha, scale = beta) + plgamma(crit[1], shape = true_alpha, scale = beta)
}

alpha_values = seq(0.5, 3, by = 0.05)

pwr_unbiased = sapply(alpha_values, find_power, crit = crit_unbiased)
pwr_tail = sapply(alpha_values, find_power, crit = crit_tail)
pwr_point = sapply(alpha_values, find_power, crit = crit_point)
```

```{r}
plot(alpha_values, pwr_unbiased)
plot(alpha_values, pwr_tail)
plot(alpha_values, pwr_point)
```






