---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(reshape2)
library(tidyverse)
library(GGally)
library(ggtext)
library(glue)
```

```{r}
dmodel <- function(x, mu){
  dpois(x, mu)
}

pmodel <- function(x, mu){
  ppois(x, mu)
}

```

```{r}
p_val_a <- function(x, mu){
  pr_tail_l = pmodel(x, mu)
  ## Use 1 - tail prob but add point prob
  pr_tail_r = 1 - pr_tail_l + dmodel(x, mu)
  
  p_val = 2 * min(pr_tail_l, pr_tail_r, 1/2)
  p_val
}

p_val_b <- function(x, mu){
  # Implementation assumes a decreasing point probability P(X = x) for increasing x after the mode has passed
  W_x = dmodel(x, mu)
  p_val = 1
  
  # Removing probabilites lower than P(X = x)
  y = 0
  cond = TRUE
  while(cond){
    W_y = dmodel(y, mu)
    if(W_y > W_x){
      # Removing the probability
      p_y = W_y
      p_val = p_val - p_y
    }
    else{
      # Checking if the loop should be ended
      ## By being in the loop we know that W_y <= W_x
      mode = floor(mu)
      passed_mode = (y > mode)
      cond = !passed_mode
    }
    # Preparing next round
    y = y +1
  }
  p_val
}

p_val_b_power <- function(x, mu, alpha = .05){
  # Implementation assumes a decreasing point probability P(X = x) for increasing x after the mode has passed
  W_x = dmodel(x, mu)
  if(W_x > alpha){
    return(1)
  }
  
  p_val = 1
  
  # Removing probabilites lower than P(X = x)
  y = 0
  cond = TRUE
  while(cond){
    W_y = dmodel(y, mu)
    if(W_y > W_x){
      # Removing the probability
      p_y = W_y
      p_val = p_val - p_y
    }
    else{
      # Checking if the loop should be ended
      ## By being in the loop we know that W_y <= W_x
      mode = floor(mu)
      passed_mode = (y > mode)
      cond = !passed_mode
    }
    # Preparing next round
    y = y +1
  }
  p_val
}

p_val_c <- function(x, mu){
  p_tail_l = pmodel(x, mu)
  p_tail_r = 1- p_tail_l + dmodel(x, mu)
  epsilon = 1e-8
  
  if (p_tail_l < p_tail_r + epsilon){
    # Since the right tail has infinite support we must suggest a low enough tail value
    y_sugg = ceiling(2*mu)
    sugg_tail = 1 - pmodel(y_sugg, mu) # this will give P(X > y), i.e. P(X geq y-1)
    while(sugg_tail > p_tail_l){
      y_sugg = ceiling(2*y_sugg)
      sugg_tail = 1 - pmodel(y_sugg, mu) # this will give P(X > y), i.e. P(X geq y-1)
    }
    # After a low enough value is reached we calculate the highest smaller right tail compared to the left tail
    right_tail = max_lower_tail(y_sugg, sugg_tail, p_tail_l, mu)
    p_val = p_tail_l + right_tail
  }
  else{
    # For a left tail we can start at 0 and find the highest smaller left tail
    left_tail = max_lower_tail(0, 0, p_tail_r, mu, left_tail = TRUE)
    p_val = p_tail_r +  left_tail
  }
  if(p_val > 1){ # If the distrbution is symmetric it will count the central event twice.
    return(1)
  }
  p_val
}

max_lower_tail <- function(y_next, tail_y, W_x, mu, left_tail = FALSE, epsilon = 1e-8){
  sugg = tail_y
  y = y_next
    while(sugg < W_x + epsilon){
      tail_y = sugg # Accept suggestion
      add = dmodel(y, mu) # Calculate new point mass to be added
      sugg = sugg + add # Propose new suggestion
      if(left_tail){
        y = y + 1
      }
      else{
        y = y - 1 
      }
    }
  tail_y
}

p_val_c_power <- function(x, mu, alpha = .05){
  p_tail_l = pmodel(x, mu)
  p_tail_r = 1- p_tail_l + dmodel(x, mu)
  epsilon = 1e-8
  
  # Giving immediate non-significance if W_x is too high
  if(min(p_tail_l, p_tail_r) > alpha){
    return(1)
  }
  
  if (p_tail_l < p_tail_r + epsilon){
    # Since the right tail has infinite support we must suggest a low enough tail value
    y_sugg = ceiling(2*mu)
    sugg_tail = 1 - pmodel(y_sugg, mu) # this will give P(X > y), i.e. P(X geq y-1)
    while(sugg_tail > p_tail_l){
      y_sugg = ceiling(2*y_sugg)
      sugg_tail = 1 - pmodel(y_sugg, mu) # this will give P(X > y), i.e. P(X geq y-1)
    }
    # After a low enough value is reached we calculate the highest smaller right tail compared to the left tail
    right_tail = max_lower_tail(y_sugg, sugg_tail, p_tail_l, mu)
    p_val = p_tail_l + right_tail
  }
  else{
    # For a left tail we can start at 0 and find the highest smaller left tail
    left_tail = max_lower_tail(0, 0, p_tail_r, mu, left_tail = TRUE)
    p_val = p_tail_r +  left_tail
  }
  if(p_val > 1){ # If the distrbution is symmetric it will count the central event twice.
    return(1)
  }
  p_val
}

p_val_d <- function(x, mu) {
  exp_val = mu
  W_x = abs(x - mu)
  
  # Get all discrete values y with lower W_y
  r = floor(mu + W_x)
  l = ceiling(mu - W_x)
  
  # Handeling ties
  if(mu + W_x == round(mu + W_x)){
    if(mu - W_x == round(mu - W_x)){
      # We are in the tied sceneraio and we want to either exclude y = l depending on if X = l or x = r
      if(x == r){
        #l = l -1
      }
      else{
        
      }
    }
  }
  
  # Rejection region will be x lower than l
  # and x higher than r
  if(l <= 0){
    p_val = 1 - ppois(r-1, mu) # 1 - P(X <= r-1) =  P(X > r-1) = P(X >= r)
    return(p_val)
  }
  p_val = 1 - ppois(r-1, mu) + ppois(l, mu) # 1 - P(X <= r-1) + P(X <= l) = P(X >= r) + P(X <= l)
  if(p_val > 1){
    return(1)
  }
  p_val
}
```

```{r}
# Test functions for the tail method
p_val_a(3, 3)
p_val_a(5, 3)

p_val_b(3, 3)
p_val_b(5, 3)

print("____")
W_x = ppois(3, 5)

W_x

1- ppois(10, 5)

max_lower_tail(10, 1-ppois(10, 5), W_x, 5, left_tail = FALSE)

print("-----")
W_x = 1-ppois(7, 5)

W_x

ppois(0, 5)


max_lower_tail(1, ppois(0, 5), W_x, 5, left_tail = TRUE)

print("____")
```

```{r}
p_val_c(3, 3)
p_val_c(5, 3)
```

```{r}
p_val_d(3, 3)

p_val_d(5, 3)
```

```{r}
comparison_p_vals <- function(mu, n){
  p_a = NULL
  p_b = NULL
  p_c = NULL
  p_d = NULL

  for(i in 0:n){
    p_a = c(p_a, p_val_a(i, mu))
    p_b = c(p_b, p_val_b(i, mu))
    p_c = c(p_c, p_val_c(i, mu))
    p_d = c(p_d, p_val_d(i, mu))
  }
  
  df <- data.frame(p_a, p_b, p_c, p_d)
  colnames(df) <- c("​Double tail", "Point", "Tail", "Distance")  #Added zero width space for "Double tail" to be shown first in plot
  df["x_val"] <- 0:n
  
  df
}

df <- comparison_p_vals(12, 20)

df %>%
  pivot_longer(-x_val, names_to = "Method", values_to = "P") %>%
  ggplot(aes(x = factor(x_val), y = P, fill = Method), xlab = "Method") +
  geom_bar(stat = "identity", width = .75, position = "dodge") +
  theme_classic() +
  labs(x = "X", y = "p-value")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+
  geom_hline(yintercept = .05)
  #scale_x_discrete(limits = factor(13:28))
  

df %>%
  pivot_longer(-x_val, names_to = "Method", values_to = "P") %>%
  ggplot(aes(x = factor(x_val), y = -log(P), fill = Method), xlab = "Method") +
  geom_bar(stat = "identity", width = .75, position = "dodge") +
  theme_classic() +
  labs(x = "X", y = "- log(p)")+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+
  #scale_x_discrete(limits = factor(13:28))
  geom_hline(yintercept = -log(5e-2))
```

```{r}
power_calc_poisson_null_hyp_true <- function(method, mu, a){
  power = 1
  n = ceiling(max(3*mu, mu^2)) # This is kind of dodgy
  for(x in 0:n){
    p_val = method(x, mu)
    if(p_val > a){
      power = power - dmodel(x, mu)
    }
  }
  power
}

power_calc_poisson_null_hyp_true(p_val_b, 10, .05)
```

```{r}
compare_power_null_hyp_true <- function(P){
  b_double = NULL
  b_point = NULL
  b_tail = NULL
  b_dist = NULL

  for(p in P){
    # Calculate power
    power_double = power_calc_poisson_null_hyp_true(p_val_a, p, .05)
    power_point = power_calc_poisson_null_hyp_true(p_val_b, p, .05)
    power_tail = power_calc_poisson_null_hyp_true(p_val_c, p, .05)
    power_dist = power_calc_poisson_null_hyp_true(p_val_d, p, .05)
    
    # Add power to the list
    b_double = c(b_double, power_double)
    b_point = c(b_point, power_point)
    b_tail = c(b_tail, power_tail)
    b_dist = c(b_dist, power_dist)
  }

  df_power <- data.frame(P, b_double, b_point, b_tail, b_dist)
  df_power
}

N = 30
P = 10 *(1:N)/N

df_power_null_hyp <- compare_power_null_hyp_true(P)
```

```{r}
print(df_power_null_hyp)

ggplot(data = df_power_null_hyp)+
  geom_line(aes(x = P, y = b_dist), linetype = "twodash")+
  geom_line(aes(x = P, y = b_point), color = "red", linetype = "dotdash")+
  geom_line(aes(x = P, y = b_tail), color = "darkgreen", linetype = "dotted")+
  geom_line(aes(x = P, y = b_double), color = "blue", linetype = "dashed")+
  theme_classic()
```

```{r}
print(P)

X_vals = 0:20
for(x in X_vals){
  print(c(x,p_val_d(x, 9)))
}

p_val_d(3, 9)
1 - ppois(14, 9)

```
# alternate hypothesis / getting power function

```{r}
p0 = 8.6
power_calc_poisson_alt <- function(method, p_true, a, p_0 = p0){
  power = 1
  # subtract the probability of being in the acceptance region
  n = ceiling(max(3*p_0, p_0^2)) # This is kind of dodgy
  for(x in 0:n){
    p_val = method(x, p_0)
    if(p_val > a){
      # The null hypothesis is not rejected in this case
      power = power - dpois(x, p_true)
    }
  }
  power
}

N = 100
alpha = .05
P = 20*(0:N)/N
b_double = NULL
b_point = NULL
b_tail = NULL
b_dist = NULL

for(p in P){
  # Calculate power
  power_double = power_calc_poisson_alt(p_val_a, p, alpha)
  power_point = power_calc_poisson_alt(p_val_b_power, p, alpha)
  power_tail = power_calc_poisson_alt(p_val_c_power, p,  alpha)
  power_dist = power_calc_poisson_alt(p_val_d, p, alpha)
    
  # Add power to the list
  b_double = c(b_double, power_double)
  b_point = c(b_point, power_point)
  b_tail = c(b_tail, power_tail)
  b_dist = c(b_dist, power_dist)
}

df_power <- data.frame(P, b_double, b_point, b_tail, b_dist)
```


```{r}
colnames(df_power) <- c("P", "​Double tail", "Point", "Tail", "Distance") 

df_power %>%
  pivot_longer(cols = -P, values_to = "Power", names_to = "Method") %>%
  ggplot()+
  geom_line(aes(x = P, y = Power, colour = Method, linetype = Method))+
  labs(x= "*P*", title = glue("*P*<sub>0</sub> = {p0}"))+
  theme(axis.title = element_markdown(), title = element_markdown())
  
```



# Surface / heatmap plots
```{r}
power_surface <- function(method, max_p, N, a){
  power_mat <- matrix(0, N+1, N+1)
  for(i in 0:N){
    p_1 = max_p*i/N
    for(j in 0:N){
      p_2 = max_p*j/N
      power_ij = power_calc_poisson_alt(method, p_2, a, p_1)
      power_mat[i, j] <- power_ij
    }
  }
  power_mat
}

power_surf_a <- power_surface(p_val_a, 20, 50, .05)
power_surf_b <- power_surface(p_val_b_power, 20, 50, .05)
power_surf_c <- power_surface(p_val_c_power, 20, 50, .05)
power_surf_d <- power_surface(p_val_d, 20, 50, .05)
```


```{r}
make_heatmap<- function(df){
  melt_df = melt(df)
  colnames(melt_df) <- c("x", "y", "power_diff")
  plot <- ggplot(melt_df, aes(x = x/sqrt(length(x)), y = y/sqrt(length(y)), fill = power_diff))+
    geom_tile()+
    scale_fill_gradient2(low = "green", mid = "white", high = "red", limits = c(-.1, .1))+
    labs(x = "P_0", y = "True p")+
    theme_classic()
  return(plot)
}

plotList = list()

plotList[[1]] = make_heatmap(power_surf_a - power_surf_a)
plotList[[2]] = NULL
plotList[[3]] = NULL
plotList[[4]] = NULL
plotList[[5]] = make_heatmap(power_surf_a - power_surf_b)
plotList[[6]] = make_heatmap(power_surf_b - power_surf_b) 
plotList[[7]] = NULL
plotList[[8]] = NULL
plotList[[9]] = make_heatmap(power_surf_a - power_surf_c)
plotList[[10]] = make_heatmap(power_surf_b - power_surf_c)
plotList[[11]] = make_heatmap(power_surf_c - power_surf_c) 
plotList[[12]] = NULL
plotList[[13]] = make_heatmap(power_surf_a - power_surf_d)
plotList[[14]] = make_heatmap(power_surf_b - power_surf_d)
plotList[[15]] = make_heatmap(power_surf_c - power_surf_d)
plotList[[16]] = make_heatmap(power_surf_d - power_surf_d)

plotList[[5]]

ggmatrix(plotList, 4, 4,
         xAxisLabels = c("Double tail", "Point", "Tail", "Distance"),
         yAxisLabels = c("Double tail", "Point", "Tail", "Distance"), 
         legend = grab_legend(plotList[[1]]))
```






