---
title: "power_binom_p_test"
author: "Olai Gaarn Skogen"
date: "2024-09-10"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(reshape2) 
library(tidyverse) 
library(plotly) #3d plots
library(GGally) #ggmatrix
library(glue) 
library(ggtext)
```

## Model for binomial

```{r}
dmodel <- function(x, n, p){
  dbinom(x, n, p)
}

pmodel <- function(x, n, p, tail_left = TRUE){
  pbinom(x, n, p, tail_left)
}

sample_space <- function(n){
  0:n
}

expected_val_model <- function(n, p){
  n*p
}

```


## Methods for computing p_value
```{r}
p_val_a <- function(x, n, p){
  pr_tail_l = pmodel(x, n, p, tail_left = TRUE)
  ## Use 1 - tail prob but add point prob
  pr_tail_r = 1 - pr_tail_l + dmodel(x, n, p)
  
  p_val = 2 * min(pr_tail_l, pr_tail_r, 1/2)
  p_val
}

p_val_a(7, 10, 0.7)
```

```{r}
p_val_b <- function(x, n, p, multi_modal = TRUE){
  W_x = dmodel(x, n, p)
  
  S = sample_space(n)
  p_val = 0
  
  if (multi_modal){
    # If multimodal makes this a bad for this p-method
    for(y in S){
      W_y = dmodel(y, n, p)
      if(W_y > W_x){
      }
      else{
        p_y = W_y
        p_val = p_val + p_y
      }
    }
  }
  else{
    #WIP of effectivised computation
  }
  
  p_val
}

p_val_b(3, 10, 0.3, TRUE)
```

```{r}
# Assuming point mass function
p_val_c <- function(x, n, p){
  p_tail_l = pmodel(x, n, p, tail_left = TRUE)
  p_tail_r = 1 - p_tail_l + dmodel(x, n, p)
  epsilon = 1e-8
  if (p_tail_l < p_tail_r + epsilon){
    # Add the maximum right tail that is smaller than left tail
    ## Start with 0 tail and add one point mass at a time until it grow bigger than left tail
    r_tail_max_smaller = 0
    y = n
    sugg = r_tail_max_smaller
    while(sugg < p_tail_l + epsilon){
      r_tail_max_smaller = sugg # Accept suggestion
      r_add = dmodel(y, n, p) # Calculate new point mass to be added
      sugg = sugg + r_add # Propose new suggestion
      y = y - 1 # Take one lower y-value
    }
    p_val = p_tail_l +  r_tail_max_smaller
  }
  else{
    # Do the same thing but find maximum smaller left tail instead of right
    l_tail_max_smaller = 0
    y = 0
    sugg = l_tail_max_smaller
    while(sugg < p_tail_r + epsilon){
      l_tail_max_smaller = sugg # Accept suggestion
      l_add = dmodel(y, n, p) # Calculate new point mass to be added
      sugg = sugg + l_add # Propose new suggestion
      y = y + 1 # Take one higher y-value
    }
    p_val = p_tail_r +  l_tail_max_smaller
  }
  if(p_val > 1){ # If the distrbution is symmetric it will count the central event twice.
    return(1)
  }
  p_val
}

p_val_c(7, 10, 0.68)
```

```{r}
# Modifications of methods for optimized power calc
p_val_c_power <- function(x, n, p, a = 0.05){
  # This function will determine if the given experiment and data resulted in a rejection or not wrt to the hypothesis test/significance level
  p_tail_l = pmodel(x, n, p)
  p_tail_r = 1- p_tail_l + dmodel(x, n, p)
  epsilon = 1e-8
  if (p_tail_l < p_tail_r + epsilon){
    if(p_tail_l > a){
      # If the lowest tail value is higher than the significance level the null hypothesis is not rejected
      return(1)
    }
    if(2*p_tail_l < a){
      # If the highest tail value you add to the p_value is lower than half the null hypthesis is rejected
      return(0)
    }
    # Add the maximum right tail that is smaller than left tail
    ## Start with 0 tail and add one point mass at a time until it grow bigger than left tail
    r_tail_max_smaller = 0
    y = n
    sugg = r_tail_max_smaller
    while(sugg < p_tail_l + epsilon){
      r_tail_max_smaller = sugg # Accept suggestion
      r_add = dmodel(y, n, p) # Calculate new point mass to be added
      sugg = sugg + r_add # Propose new suggestion
      y = y - 1 # Take one lower y-value
    }
    p_val = p_tail_l +  r_tail_max_smaller
  }
  else{
    if(p_tail_r > a){
      # If the lowest tail value is higher than the significance level the test fails necessairly
      return(1)
    }
    if(2*p_tail_r < a){
      # If the highest tail value you add to the p_value is lower than half the null hypthesis is rejected
      return(0)
    }
    # Do the same thing but find maximum smaller left tail instead of right
    l_tail_max_smaller = 0
    y = 0
    sugg = l_tail_max_smaller
    while(sugg < p_tail_r + epsilon){
      l_tail_max_smaller = sugg # Accept suggestion
      l_add = dmodel(y, n, p) # Calculate new point mass to be added
      sugg = sugg + l_add # Propose new suggestion
      y = y + 1 # Take one higher y-value
    }
    p_val = p_tail_r +  l_tail_max_smaller
  }
  if(p_val > 1){ # If the distrbution is symmetric it will count the central event twice.
    return(1)
  }
  p_val
}

```


```{r}
p_val_d <- function(x, n, p) {
  exp_val = expected_val_model(n, p)
  W_x = abs(x - exp_val)
  
  p_val = 0
  S = sample_space(n)
  for(y in S){
    W_y = abs(y - exp_val)
    if(W_y < W_x){}
    else{
      p_val = p_val + dmodel(y, n, p)
    }
  }
  
  # håndtering av ties
  if(2*W_x == round(2*W_x)){
    # p_val = p_val - dmodel(exp_val-W_x, n, p)
  }
  
  p_val
}

p_val_d(7, 10, 0.7)
```

## Calculating power

```{r}
power_calc_binom <- function(method, n, p, a){
  power = 0
  for(x in 0:n){
    p_val = method(x, n, p)
    if(p_val < a){
      power = power + dbinom(x, n, p)
    }
  }
  power
}

power_calc_binom(p_val_d, 10, 0.82, 0.05)

N = 1000
P = 0:N/N
b_double = NULL
b_point = NULL
b_tail = NULL
b_dist = NULL

for(p in P){
  # Calculate power
  power_double = power_calc_binom(p_val_a, 20, p, .05)
  power_point = power_calc_binom(p_val_b, 20, p, .05)
  power_tail = power_calc_binom(p_val_c_power, 20, p, .05)
  power_dist = power_calc_binom(p_val_d, 20, p, .05)
    
  # Add power to the list
  b_double = c(b_double, power_double)
  b_point = c(b_point, power_point)
  b_tail = c(b_tail, power_tail)
  b_dist = c(b_dist, power_dist)
}

df_power <- data.frame(P, b_double, b_point, b_tail, b_dist)
```
```{r}
ggplot(data = df_power)+
  geom_point(aes(x = P, y = b_tail))+
  labs(x = "*\u03B8*<sub>0</sub>", y = "Type 1 Error", title = "Tail method")+
  theme(axis.title = element_markdown(size = 14), axis.text = element_text(size = 12), title = element_markdown(size = 16), legend.title = element_markdown(size = 14), legend.text = element_text(size = 12))

```


# Code to investigate rejection areas, especially for distance method
```{r}
rej_area_binom <- function(method, n, p, a){
  power = 0
  is_rej_area = NULL
  
  for(x in 0:n){
    p_val = method(x, n, p)
    if(p_val < a){
      power = power + dbinom(x, n, p)
      is_rej_area = c(is_rej_area, 1)
    }
    else{
      is_rej_area = c(is_rej_area, 0)
    }
  }
  is_rej_area
}

n = 20
N = 1000
mat = matrix(0, nrow = N +1, ncol = n + 1)

for(i in 0:N){
  p = i/N
  rej_area_i = rej_area_binom(p_val_d, n, p, .05)
  mat[i+1,] = rej_area_i
}

df_rej_area = melt(mat)
colnames(df_rej_area) <- c("x", "y", "value")
```

```{r}

df_rej_area

df_rej_size = apply(mat, 1, sum)

ggplot(data = df_rej_area, aes(x = x/N, y = y, fill = as.factor(value))) + 
  geom_tile()+
  labs(y = "X", x = "P", title = "Rejection area distance method", fill = "Rejection")

plot(x = P, y = df_rej_size, title(main = "Size of rejection area"), ylab = "#points in rejection area")
  
```
# Testing for a cross-section with p_0 = 0.71 and a = 0.5
```{r}
power_calc_binom_alt <- function(method, n, p_true, a, p_0 = 0.71){
  power = 0
  for(x in 0:n){
    p_val = method(x, n, p_0)
    if(p_val < a){
      power = power + dbinom(x, n, p_true)
    }
  }
  power
}

N = 1000
n = 10
alpha = .05
P = (0:N)/N
b_double = NULL
b_point = NULL
b_tail = NULL
b_dist = NULL

for(p in P){
  # Calculate power
  power_double = power_calc_binom_alt(p_val_a, n, p, alpha)
  power_point = power_calc_binom_alt(p_val_b, n, p, alpha)
  power_tail = power_calc_binom_alt(p_val_c_power, n, p, alpha)
  power_dist = power_calc_binom_alt(p_val_d, n, p, alpha)
    
  # Add power to the list
  b_double = c(b_double, power_double)
  b_point = c(b_point, power_point)
  b_tail = c(b_tail, power_tail)
  b_dist = c(b_dist, power_dist)
}

df_power_slice <- data.frame(P, b_double, b_point, b_tail, b_dist)
```

```{r}
colnames(df_power_slice) <- c("P", "​Double tail", "Point", "Tail", "Distance")

df_power_slice %>%
pivot_longer(cols = -P, values_to = "Power", names_to = "Method") %>%
  ggplot()+
  geom_line(aes(x = P, y = Power, colour = Method, linetype = Method))+
  labs(x= "True \u03b8", title = "\u03b8<sub>0</sub> = 0.71, *n* = 10")+
  theme(axis.title = element_markdown(size = 14), axis.text = element_text(size = 12), title = element_markdown(size = 16), legend.title = element_markdown(size = 14), legend.text = element_text(size = 12))
```
```{r}
power_surface <- function(method, n, N, a){
  power_mat <- matrix(0, N+1, N+1)
  for(i in 0:N){
    p_hyp = i/N
    for(j in 0:N){
      p_act = j/N
      power_ij = power_calc_binom_alt(method, n, p_true = p_act, a = a, p_0 = p_hyp)
      power_mat[i+1, j+1] <- power_ij
    }
  }
  power_mat
}

power_surf_a <- power_surface(p_val_a, 10, 200, .05)
power_surf_b <- power_surface(p_val_b, 10, 200, .05)
power_surf_c <- power_surface(p_val_c_power, 10, 200, 0.05)
power_surf_d <- power_surface(p_val_d, 10, 200, .05)

```

```{r}
make_heatmap<- function(df){
  melt_df = melt(df)
  colnames(melt_df) <- c("x", "y", "power_diff")
  plot <- ggplot(melt_df, aes(x = x/sqrt(length(x)), y = y/sqrt(length(y)), fill = power_diff))+
    geom_tile()+
    scale_fill_gradient2(low = "green", mid = "white", high = "red", limits = c(-1, 1))+
    labs(x = "\u03b8<sub>0</sub>", y = "True \u03b8", fill = "\u0394 Power")+
    theme(axis.title = element_markdown(size = 14), axis.text = element_text(size = 12), title = element_markdown(size = 16), legend.title = element_markdown(size = 14), legend.text = element_text(size = 12))+
    scale_x_continuous(breaks = c(0, 0.5, 1)) +
    scale_y_continuous(breaks = c(0, 0.5, 1))
  return(plot)
}

plotList = list()

plotList[[1]] = make_heatmap(power_surf_a - power_surf_a)
plotList[[2]] = NULL
plotList[[3]] = NULL
plotList[[4]] = NULL
plotList[[5]] = make_heatmap(power_surf_a - power_surf_b)
plotList[[6]] = make_heatmap(power_surf_b - power_surf_b) 
plotList[[7]] = NULL
plotList[[8]] = NULL
plotList[[9]] = make_heatmap(power_surf_a - power_surf_c)
plotList[[10]] = make_heatmap(power_surf_b - power_surf_c)
plotList[[11]] = make_heatmap(power_surf_c - power_surf_c) 
plotList[[12]] = NULL
plotList[[13]] = make_heatmap(power_surf_a - power_surf_d)
plotList[[14]] = make_heatmap(power_surf_b - power_surf_d)
plotList[[15]] = make_heatmap(power_surf_c - power_surf_d)
plotList[[16]] = make_heatmap(power_surf_d - power_surf_d)

plotList[[10]]

ggmatrix(plotList, 4, 4,
         xAxisLabels = c("Double tail", "Point", "Tail", "Distance"),
         yAxisLabels = c("Double tail", "Point", "Tail", "Distance"), 
         legend = grab_legend(plotList[[1]]))
```

```{r}
print((power_surf_b - power_surf_c)[,78])
```


```{r}
plot_power <- plot_ly(z = power_surf_a, type = "surface")
plot_power <- plot_power %>% add_surface(z = power_surf_b, colorscale = list(c(0, 1), c("pink", "red")))
plot_power <- plot_power %>% add_surface(z = power_surf_c, colorscale = list(c(0, 1), c("pink", "red")))
#plot_power <- plot_power %>% add_surface(z = power_surf_d, colorscale = list(c(0, 1), c("tan", "blue")))
plot_power
```


