---
title: "R Notebook"
output: html_notebook
---

```{r}
source("p_vals_disc.R")
library(tidyverse)
library(ggplot2)
```


```{r}
n = 10
p0 = 1/6
significance_value_test = 0.05

pT <- function(x){pbinom(x, n, p0)}
dT <- function(x){dbinom(x, n, p0)}
intT <- function(x){x*dbinom(x, n, p0)}
E_T <- sum(sapply(0:n, intT))
```

# Checking against Dunne et al (1996)
```{r}
calc_all_p_vals_binom <- function(n, p0){
  
  pT <- function(x){pbinom(x, n, p0)}
  dT <- function(x){dbinom(x, n, p0)}
  intT <- function(x){x*dbinom(x, n, p0)}
  E_T <- sum(sapply(0:n, intT))
  bndry_min = -1
  bndry_max = n +1
  
  x_vec = 0:n
  unb_vec = x_vec*0
  point_vec = x_vec*0
  tail_vec = x_vec*0
  
  for (i in 1:(n+1)){
    unb_vec[i] = unbiased_p_val(x_vec[i], dT, pT, intT, E_T, bndry_min, bndry_max)
    point_vec[i] = point_p_val(x_vec[i], dT, bndry_min, bndry_max)
    tail_vec[i] = tail_p_val(x_vec[i], dT, pT, bndry_min, bndry_max)
  }
  
  df <- data.frame(x_vec, unb_vec, point_vec, tail_vec)
  return(df)
}
```

```{r}
df_pvals <- calc_all_p_vals_binom(n, p0)

colnames(df_pvals) <- c("x", "Unbiased", "Point", "Tail")
df_pvals

df_pvals %>%
  pivot_longer(-x, names_to = "Method", values_to = "P_value") %>%
  ggplot(aes(x = x, y = P_value, fill = Method), xlab = "Method") +
  geom_bar(stat = "identity", width = .75, position = "dodge") +
  theme_classic() +
  labs(x = "X", y = "P-value")+
  theme(axis.text.x = element_text(size = 12, angle = 0, vjust = 0.5), axis.text.y = element_text(size = 12), axis.title = element_text(size = 14), legend.text = element_text(size = 12), legend.title = element_text(size = 14))+
  #scale_x_discrete(limits = factor(13:28))
  geom_hline(yintercept = 5e-2)

df_pvals %>%
  pivot_longer(-x, names_to = "Method", values_to = "P_value") %>%
  ggplot(aes(x = x, y = -log(P_value), fill = Method), xlab = "Method") +
  geom_bar(stat = "identity", width = .75, position = "dodge") +
  theme_classic() +
  labs(x = "X", y = "- log(p-value)")+
  theme(axis.text.x = element_text(size = 12, angle = 0, vjust = 0.5), axis.text.y = element_text(size = 12), axis.title = element_text(size = 14), legend.text = element_text(size = 12), legend.title = element_text(size = 14))+
  #scale_x_discrete(limits = factor(13:28))
  geom_hline(yintercept = -log(5e-2))
```




```{r}
bisection_discrete <- function(f, lower, upper, ...){
  endCond = FALSE
  
  lower = round(lower)
  upper = round(upper)
  print("yo debugger")
  print(c(lower, upper))
  fl = f(lower, ...)
  fu = f(upper, ...)
  print(c(fl, fu))
  
  if(fl * fu > 0){
    print("Edge case")
    # want to check if we want to add the whole tail
    
    # left side
    fl_minus = f(lower -1, ...)
    print(fl_minus)
    if(fl_minus * fl < 0){
      print(c(fl_minus, fl))
      if(fl > 0){
        return(lower)
      }
      else{
        return(lower -1)
      }
    }
    
    # right side
    fu_plus = f(upper+1, ...)
    if(fu * fu_plus < 0){
      print(c(fu, fu_plus))
      if(fu > 0){
        return(upper)
      }
      else{
        return(upper +1)
      }
    }
    
    # Other handling
    stop("Error : The endpoints are not of opposite sign")
  }
  while(!endCond){
    mid = round((lower + upper)/ 2)
    fm = f(mid, ...)
    if(fm * fl > 0){
      lower = mid
      fl = fm
    }
    else{
      upper = mid
      fu = fm
    }
    print(c(lower, mid, upper))
    if(upper - lower == 1){
      endCond = TRUE
    }
  }
  print(c(fl, fu))
  if(fl < 0){
    return(lower)
  }
  else{
    return(upper)
  }
  # add [1] if low value is wanted and [2] if high value is wanted
}

# 1. Find the critical values of t such that the p-values are below the significance level
find_crit_values <- function(method, significance_value,  ..., mid_point){
  
  modified_func <- function(t, ...){method(t, ...) - significance_value}
  # TODO : Update so we get automatic guess for mid-point
  t_1 <- bisection_discrete(modified_func, lower = -1, upper = floor(mid_point), ...)
  print("critical vals 1")
  print(t_1)
  t_2 <- bisection_discrete(modified_func, lower = ceiling(mid_point), upper = n+1, ...)
  print(t_2)
  return(c(t_1, t_2))
}

# It is important that they are passed as objects and not written directly as bndry_min = bndry_min in the function

bndry_min = -1
bndry_max = n+1
crit_binom_unb <- find_crit_values(unbiased_p_val, significance_value = significance_value_test, dT = dT, pT = pT, intT = intT, E_T = E_T, bndry_min = bndry_min, bndry_max = bndry_max, mid_point = E_T)
```

```{r}
true_pvals = c(seq(0, 0.5, by = 0.005), 1/3)

pwr_calc_binom <- function(true_p_val, crit_vals){
  pbinom(crit_vals[1], n, true_p_val) + 1 - pbinom(crit_vals[2] -1, n, true_p_val)
}

pwr_vals_unb = sapply(true_pvals, pwr_calc_binom, crit_binom_unb)

crit_binom_unb
pwr_calc_binom_unbiased(1/3)
plot(true_pvals, pwr_vals_unb)
```

```{r}
bndry_min = -1
bndry_max = n+1
crit_binom_tail <- find_crit_values(tail_p_val, significance_value = significance_value_test, dT = dT, pT = pT, bndry_min = bndry_min, bndry_max = bndry_max, mid_point = E_T)
crit_binom_tail
```

```{r}
bndry_min = 0
bndry_max = n
crit_binom_point <- find_crit_values(point_p_val, significance_value = significance_value_test, dT = dT, bndry_min = bndry_min, bndry_max = bndry_max, mid_point = E_T)
crit_binom_point
```

```{r}
pwr_vals_tail = sapply(true_pvals, pwr_calc_binom, crit_binom_tail)

plot(true_pvals, pwr_vals_tail)

pwr_vals_point = sapply(true_pvals, pwr_calc_binom, crit_binom_point)

plot(true_pvals, pwr_vals_point)
```

```{r}
df_pwr <- data.frame(true_pvals, pwr_vals_unb, pwr_vals_point, pwr_vals_tail)
df_pwr

colnames(df_pwr) <- c("Parameter", "UMPU", "Point", "Tail") 

df_pwr %>%
  pivot_longer(cols = -"Parameter", values_to = "Power", names_to = "P_value") %>%
  ggplot()+
  geom_line(aes(x = Parameter, y = Power, colour = P_value, linetype = P_value))+
  geom_vline(xintercept = p0)+
  labs(title = "Power functions - Binomial parameter", x = "theta", y = "Power") +
 theme(title = element_text(size = 14),
       axis.title = element_text(size = 14),
       legend.text = element_text(size = 14))

```






